name: List Directories

on:
  push:
    branches:
      - main

jobs:
  list-dirs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List all directories
        run: |
          find . -type d
          ls -la
          mkdir olum
          ls -la